### ISSUE TITLE
File re-organization

### ISSUE THREAD

**Issue by DevHyperCoder** [thebinsohail/WebFolio#6]
From Readme.md num 1.
``` Need someone to organize the code in the cleaner way i.e files in separate folders```

i will do it 😄

**Comment by thebinsohail** [comment]
I'll be glad if you do that 😊

**Comment by DevHyperCoder** [comment]
Can we also switch out to yarn? @thebinsohail

**Comment by thebinsohail** [comment]
Glad to have your contribution ! <3 💯
