### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by thebinsohail** [thebinsohail/WebFolio#7]
Making the web app more responsive specially the experience section

**Comment by mzilley** [comment]
@thebinsohail I can help ya with this. Could you assign me the issue?

**Comment by thebinsohail** [comment]
You're being assigned

**Comment by thebinsohail** [comment]
> @thebinsohail I can help ya with this. Could you assign me the issue?

Are you doing your thing broo?

**Comment by thebinsohail** [comment]
We'll open this issue if we get any response
